name: Lifeanarchy
version: '${project.version}'
main: org.lifeanarchy.LightLag
api-version: 1.15
load: STARTUP
loadbefore: [ start.sh ]
authors: [ House_1, 254nm ]
description: Just a patch for lightlag
